#!/bin/bash

function error 
{
	echo $1 >&2
	exit 1
}

function is_switch_running
{
	ovs-appctl version >/dev/null 2>&1
}

if [ -z "$1" ]; then
	error "Usage: ${0##*/} <bridge name>" 
fi

W=
if ! is_switch_running; then
	W="--no-wait"
fi

if ovs-vsctl br-exists "$1"; then
	ovs-vsctl $W del-br $1
fi
